### ISSUE TITLE
Using struct as element

### ISSUE THREAD

**Issue by glennpierce** [m-labs/rust-atomic_ring_buffer#2]
Hi I have a struct defined like

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ElementStreamFormat(pub DateTime<UTC>, pub f64);

However, when trying to create a ring buffer I get

let buffer = Arc::new(AtomicRingBuffer::new([ElementStreamFormat; 100]));

the trait `atomic_ring_buffer::InvariantAsMut<[_]>` is not implemented for `[fn(chr
ono::DateTime<chrono::UTC>, f64)

What do I need to allow struct to be placed in the ring buffer or tuples if possible ?

Thanks

**Comment by whitequark** [comment]
@glennpierce This is not a direct answer to your question but do not use this crate as it contains bugs severe enough that make it completely unusable.

**Comment by sp-1234** [comment]
> do not use this crate as it contains bugs severe enough that make it completely unusable

Maybe it's worth mentioning in the README?

**Comment by whitequark** [comment]
yeah
