### ISSUE TITLE
Broken links in Cargo.toml metadata

### ISSUE THREAD

**Issue by Wallacoloo** [m-labs/rust-atomic_ring_buffer#3]
`Homepage` is set to https://github.com/m-labs/atomic_ring_buffer, whereas the actual location is **rust-**atomic_ring_buffer. Similar for the repository/documentation fields.

Should be an easy fix, but it requires a push to Crates.io to update the broken links there too.

**Comment by whitequark** [comment]
This crate is completely broken, I should probably yank it instead

**Comment by Wallacoloo** [comment]
@whitequark Ah, shoot. Thanks for being upfront about that though.

I don't suppose you could recommend any alternative crates? I need to store characters received in a UART interrupt into some buffer to pass them up to the main context. No actual multithreading; just interrupts, but preferably in a no-std environment.

**Comment by whitequark** [comment]
Yeah, that's exactly what I was writing this for, and I failed. Come to think of it I never actually figured out what's broken or wrong in my assumptions. If you ever figure this out *please* tell me!
